########面试题：一个线程池中的线程异常了，那么线程池会怎么处理这个线程？#########

总结一下,当一个线程池里面的线程异常后:

当执行方式是execute时,可以看到堆栈异常的输出。

当执行方式是submit时,堆栈异常没有输出。但是调用Future.get()方法时，可以捕获到异常。

不会影响线程池里面其它线程的正常执行。

线程池会把这个线程移除掉，并创建一个新的线程放到线程池中。
(ThreadPoolExecutor类中的processWorkerExit()方法源码说明中写道： 如果线程池中某个线程出现异常，则把该线程从线程池移除掉,并创建一个新的线程放入池中)

不要背答案，要理解，要深入，上面说完后记得再问问面试官，需要我从源码的角度讲一讲吗?这逼装的，礼貌而不失风度

=====================================================================================











### Executors各个方法的弊端：
```
public static ExecutorService newFixedThreadPool(int nThreads) {
        return new ThreadPoolExecutor(nThreads, nThreads,
                                      0L, TimeUnit.MILLISECONDS,
                                      new LinkedBlockingQueue<Runnable>());
}
```
```
public static ExecutorService newSingleThreadExecutor() {
        return new FinalizableDelegatedExecutorService
            (new ThreadPoolExecutor(1, 1,
                                    0L, TimeUnit.MILLISECONDS,
                                    new LinkedBlockingQueue<Runnable>()));
}
```
- newFixedThreadPool和newSingleThreadExecutor;
   主要问题是堆积的请求和处理队列可能会耗费非常大的内存，甚至OOM
   



```
public static ExecutorService newCachedThreadPool() {
        return new ThreadPoolExecutor(0, Integer.MAX_VALUE,
                                      60L, TimeUnit.SECONDS,
                                      new SynchronousQueue<Runnable>());
}
```
```
public ScheduledThreadPoolExecutor(int corePoolSize) {
        super(corePoolSize, Integer.MAX_VALUE, 0, NANOSECONDS,
              new DelayedWorkQueue());
}
```   
- newCachedThreadPool和newScheduledThreadPool;
   主要问题是线程数最大数是Integer.MAX_VALUE,可能会创建非常多的线程，甚至OOM   
