```text
org.springframework.dao.CannotAcquireLockException: StatementCallback; SQL [
insert into t_log_http_status_minute5 (domain,status,request,record_time,provider) 
values ('1.com','3xx','6','2021-04-28 06:25:00','aa'),
       ('2.com','4xx','7','2021-04-28 06:27:00','cc') 
       
ON DUPLICATE KEY UPDATE status=VALUES(status), request=VALUES(request), record_time=VALUES(record_time), provider=VALUES(provider)
]; 
nested exception is com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: 
Lock wait timeout exceeded; 
try restarting transaction;

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:262)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.       java:72)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1442)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:387)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:522)
	at com.asia.logscheduler.util.JdbcUtil.addStatusCode(JdbcUtil.java:262)
	at com.asia.logscheduler.util.JdbcUtil$$FastClassBySpringCGLIB$$d1fd29a9.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:91)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:164)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:118)
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke                                          (AnnotationAwareRetryOperationsInterceptor.java:153)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.asia.logscheduler.util.JdbcUtil$$EnhancerBySpringCGLIB$$3e8cf7cf.addStatusCode(<generated>)
	at com.asia.logscheduler.service.LogCommonService.addStatusCode(LogCommonService.java:215)
	at com.asia.logscheduler.service.DomainService$3.call(DomainService.java:478)
	at com.asia.logscheduler.service.DomainService$3.call(DomainService.java:475)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:123)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1335)
	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2108)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1245)
	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:120)
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:510)
	at org.springframework.jdbc.core.JdbcTemplate$1UpdateStatementCallback.doInStatement(JdbcTemplate.java:507)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:375)
	... 21 common frames omitted
```

现象：多个组件都有定时任务，往一个表中插入数据，前一段好好的，突然某一天，所有组件都不能插入数据了，并且所有组件都会抛出上面的异常，
查询全部表数据木有响应并且不会返回，使用order by ... desc limit 1，可以查询出数据；
本来以为是多个组件操作一个表，造成死锁，其实不是；

产生原因：int类型主键达到最大值,新数据无法插入；

解决方案：修改主键类型为bigint;
```
ALTER TABLE `表名` CHANGE `id`
`id` BIGINT(20) AUTO_INCREMENT;

-- int的最大值为2147483647            《2的31次方 - 1》
-- long的最大值为9223372036854775807  《2的63次方 - 1》
```
